### ISSUE TITLE
dependabotを導入する

### ISSUE THREAD

**Issue by ohiaeni** [ohiaeni/MemoBlend#23]
## 概要
- CI / CDの環境を構築する上で便利なdependabotを利用できる環境を構築する。

## 詳細
- まずはDependabotとは何かということから取り組むべきである。
- 関連情報については、こちらのIssueにコメントする形で情報を残す。

## クローズ条件
- Dependabotが本プロジェクトに必要か判断した上で対応が完了している。
- できればOSSライブラリのアップデートに対して自動でPRを作成できるようにしてほしい。

**Comment by berry8848** [comment]
下図赤枠に"settings"が表示されない。
本来は、そこから特定リポジトリのdependabotの設定ができるが、表示されないため不可能。
表示されない理由はおそらく、MemoBlendリポジトリの所有者が賢二だから…？
![image](https://github.com/user-attachments/assets/1cdb7d4e-3d86-4d5e-9405-e9da3fa4ddf5)

間違っていたら指摘お願いします。

**Comment by ohiaeni** [comment]
@berry8848 
確かにそうかもしれない。
権利の移譲は手間なのでAssigneesを変更します。
